ticketera/app/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', home, name="home"),
    path('registrar-ticket/', registrar_ticket, name='registrar_ticket'),
    path('listar-tickets/', listar_tickets, name='listar_tickets'),
    path('exito/', exito, name='exito'),
    path('editar-ticket/<int:ticket_id>/', editar_ticket, name='editar_ticket'),
]

ticketera/ticketera/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('app.urls')),
]

ticketera/app/models.py
from django.db import models
from .opciones import SEDE_CHOICES, MODALIDAD_CHOICES, REPORTE_CHOICES

class Ticket(models.Model):
    IdTicket = models.AutoField(primary_key=True)
    Sede = models.IntegerField(choices=SEDE_CHOICES, null=True)
    Direccion = models.CharField(max_length=200)
    Area = models.CharField(max_length=200)
    Modalidad = models.IntegerField(choices=MODALIDAD_CHOICES, null=True)
    Nombre = models.CharField(max_length=200)
    Rut = models.CharField(max_length=12)
    Usuario = models.CharField(max_length=200)
    CorreoInstitucional = models.EmailField()
    Telefono = models.CharField(max_length=12)
    FechaEmision = models.DateTimeField(auto_now_add=True)
    TipoReporte = models.IntegerField(choices=REPORTE_CHOICES, null=True)
    Solicitud = models.CharField(max_length=600, default='')
    IP = models.CharField(max_length=200, blank=True, null=True)
    HOSTNAME = models.CharField(max_length=200, blank=True, null=True)
    MARCA_MODELO = models.CharField(max_length=200, blank=True, null=True)
    
    def __str__(self):
        return f"{self.IdTicket} ; {self.Usuario} ; {self.FechaEmision}"

ticketera/app/forms.py
from django import forms
from .models import *

class TicketForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = '__all__'

ticketera/app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import *
from .models import *

# Create your views here.

def home(request):
    return render(request, 'app/home.html')

def registrar_ticket(request):
    if request.method == 'POST':
        form = TicketForm(request.POST)
        if form.is_valid():
            ticket = Ticket(
                Sede=form.cleaned_data['Sede'],
                Direccion=form.cleaned_data['Direccion'],
                Area=form.cleaned_data['Area'],
                Modalidad=form.cleaned_data['Modalidad'],
                Nombre=form.cleaned_data['Nombre'],
                Rut=form.cleaned_data['Rut'],
                Usuario=form.cleaned_data['Usuario'],
                CorreoInstitucional=form.cleaned_data['CorreoInstitucional'],
                Telefono=form.cleaned_data['Telefono'],
                TipoReporte=form.cleaned_data['TipoReporte'],
                Solicitud=form.cleaned_data['Solicitud']
            )
            ticket.save()
            return redirect('exito')  # Cambia 'exito' por la URL correcta
    else:
        form = TicketForm()

    return render(request, 'app/registrar_ticket.html', {'form': form})

def listar_tickets(request):
    search_usuario = request.GET.get('search_usuario', '')
    
    if search_usuario:
        tickets = Ticket.objects.filter(Usuario__icontains=search_usuario)
    else:
        tickets = Ticket.objects.all()
    
    return render(request, 'app/listar_tickets.html', {'tickets': tickets})

def exito(request):
    return render(request, 'app/exito.html')

def editar_ticket(request, ticket_id):
    ticket = get_object_or_404(Ticket, pk=ticket_id)

    if request.method == 'POST':
        form = TicketForm(request.POST, instance=ticket)  # Pasa la instancia al formulario
        if form.is_valid():
            form.save()  # Guarda los cambios en el ticket
            return redirect('listar_tickets')  # Cambia 'listar_tickets' por la URL correcta
    else:
        form = TicketForm(instance=ticket)  # Pasa la instancia al formulario

    return render(request, 'app/editar_ticket.html', {'form': form, 'ticket': ticket})

ticketera/app/templates/app/base.html
<!DOCTYPE HTML>
<html>
<head>
    <title>TICKETERA</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    {% load static %}
    <style>
    </style>
    {% block css %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    {% endblock %}
    <link rel="stylesheet" href="{% static 'app/css/main.css' %}" />
    <link rel="stylesheet" href="{% static 'app/sass/main.scss' %}" />
    <link rel="stylesheet" href="{% static 'app/sass/libs/_breakpoints.scss' %}" />
    <link rel="stylesheet" href="{% static 'app/sass/libs/_functions.scss' %}" />
    <link rel="stylesheet" href="{% static 'app/sass/libs/_html-grid.scss' %}" />
    <link rel="stylesheet" href="{% static 'app/sass/libs/_mixins.scss' %}" />
    <link rel="stylesheet" href="{% static 'app/sass/libs/_vars.scss' %}" />
    <link rel="stylesheet" href="{% static 'app/sass/libs/_vendor.scss' %}" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.2/fullcalendar.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.2/fullcalendar.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key={{ GOOGLE_MAPS_API_KEY }}&callback=initMap" async defer></script>
</head>
<body class="is-preload">
	
    <!-- Content -->
    <div id="content">
        {% block contenido  %}
        {% if messages %}
        {% for me in messages %}
        {{ me }}
        {% endfor %}
        {% endif %}
        {% endblock %}
    </div>
    <!-- Sidebar (Hamburguesa) -->
    <div id="sidebar">
        <h1 id="logo"><a href="{% url 'home'%}">TICKETERA</a></h1>
        <div class="menu-container" id="menuContainer">
            <nav id="nav">
                <ul>
                    <li><a href="{% url 'registrar_ticket'%}">EMITIR TICKET</a></li>
                    <li><a href="{% url 'listar_tickets' %}">LISTAR TICKETS</a></li>
                </ul>
            </nav>
            <ul id="copyright">
                <li>&copy; TICKETERA.</li><li>Diseñado por: <a href="https://github.com/Deevcode">Deevcode</a></li>
            </ul>
        </div>
    </div>
    <!-- Scripts -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    {% if messages %}
    {% for me in messages %}
    <script>
        Swal.fire({
            "title": "Felicitaciones",
            "text": "{{me}}",
            "icon": "success"
        });
    </script>
    {% endfor %}
    {% endif %}
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            const menuBtn = document.getElementById('menuBtn');
            const menuContainer = document.getElementById('menuContainer');

            menuBtn.addEventListener('click', () => {
                menuContainer.classList.toggle('show');
            });
        });
    </script>
    <script src="{% static 'app/js/jquery.min.js'%}"></script>
    <script src="{% static 'app/js/browser.min.js'%}"></script>
    <script src="{% static 'app/js/breakpoints.min.js'%}"></script>
    <script src="{% static 'app/js/util.js'%}"></script>
    <script src="{% static 'app/js/main.js' %}"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    {% block js %}
    <script>
        // Aquí puedes agregar tus scripts personalizados si los tienes.
    </script>
    {% endblock %}
</body>
</html>

ticketera/app/templates/app/editar_ticket.html
{% extends 'app/base.html' %}

{% block css %}
<style>
    .edit-heading {
        font-size: 2.5rem;
        font-weight: bold;
        margin-bottom: 1rem;
    }
</style>
<style>
    /* Estilos personalizados */
    .custom-form-label {
        font-weight: bold;
    }
    .custom-form-field {
        margin-bottom: 15px;
    }
    .custom-form-submit {
        margin-top: 20px;
    }
</style>
{% endblock %}

{% block contenido %}
<div class="container mt-5">
    <h1 class="edit-heading">Editar Ticket</h1>
    <form method="post" class="needs-validation" novalidate>
        {% csrf_token %}
        {% for field in form %}
            <div class="mb-3 custom-form-field">
                <label for="{{ field.id_for_label }}" class="form-label custom-form-label">{{ field.label }}</label>
                {{ field }}
            </div>
        {% endfor %}
        <button type="button" class="btn btn-primary custom-form-submit" id="editarBtn">Guardar Cambios</button>
        <a href="{% url 'listar_tickets' %}" class="btn btn-secondary custom-form-submit">Cancelar</a>
    </form>
</div>
{% endblock %}
{% block js %}
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    // Función para mostrar un SweetAlert2 de confirmación al hacer clic en "Guardar Cambios"
    document.addEventListener('DOMContentLoaded', () => {
        const editarBtn = document.getElementById('editarBtn');
        
        editarBtn.addEventListener('click', () => {
            Swal.fire({
                title: 'Confirmar',
                text: '¿Desea guardar los cambios en el ticket?',
                icon: 'question',
                showCancelButton: true,
                confirmButtonText: 'Sí, guardar',
                cancelButtonText: 'Cancelar'
            }).then((result) => {
                if (result.isConfirmed) {
                    // Envía el formulario si el usuario confirma
                    document.querySelector('form').submit();
                }
            });
        });

        // Función para mostrar un SweetAlert2 después de enviar el formulario
        {% if success_message %}
        Swal.fire({
            title: 'Éxito',
            text: '{{ success_message }}',
            icon: 'success',
            timer: 3000,  // Auto-cerrar después de 3 segundos
            showConfirmButton: false
        });
        {% endif %}
    });
</script>
{% endblock %}

ticketera/app/templates/app/exito.html
{% extends 'app/base.html' %}

{% block contenido %}
<div class="container mt-5">
    <div class="alert alert-success" role="alert">
        ¡El ticket ha sido emitido con éxito!, Revisa la lista de tickets
    </div>
    <a href="{% url 'listar_tickets' %}" class="btn btn-primary">Volver al Inicio</a>
</div>
{% endblock %}

ticketera/app/templates/app/home.html
{% extends 'app/base.html' %}

{% load static %}

{% block js %}

{% endblock %}

{% block css %}
<style>
    /* Estilos personalizados */
    .jumbotron {
        background-color: #f8f9fa;
        padding: 2rem 1rem;
        border-radius: 0.5rem;
    }
    .ticketera-heading {
        font-size: 2.5rem;
        font-weight: bold;
        margin-bottom: 1rem;
    }
    .ticketera-description {
        font-size: 1.2rem;
        color: #6c757d;
    }
    .ticketera-cta {
        margin-top: 2rem;
    }
</style>
{% endblock %}

{% block contenido %}
<div class="container mt-5">
    <div class="jumbotron">
        <h1 class="ticketera-heading">Bienvenido a la Ticketera de Contact Center</h1>
        <p class="ticketera-description">Gestiona eficientemente las incidencias y requerimientos de los clientes con nuestra avanzada solución de ticketera.</p>
        <p class="ticketera-description">Nuestro sistema te permite registrar, gestionar y dar seguimiento a cada ticket de manera organizada y efectiva.</p>
        <a href="{% url 'registrar_ticket' %}" class="btn btn-primary btn-lg ticketera-cta">Registrar Nuevo Ticket</a>
    </div>
</div>
{% endblock %}

ticketera/app/templates/app/listar_tickets.html
{% extends 'app/base.html' %}

{% load static %}

{% block js %}

{% endblock %}

{% block css %}
<style>
    .edit-heading {
        font-size: 2.5rem;
        font-weight: bold;
        margin-bottom: 1rem;
    }
</style>
<style>
    /* Estilos personalizados */
    .no-tickets-message {
        text-align: center;
        padding: 20px;
        font-size: 1.2rem;
        color: #6c757d;
    }

    .table-container {
        overflow-x: auto;
        max-width: 100%;
    }

    .table {
        width: 100%;
        border-collapse: collapse;
    }

    .table th,
    .table td {
        padding: 10px 15px;
        vertical-align: middle;
    }

    .table thead th {
        background-color: #343a40;
        color: white;
    }

    .table tbody tr:nth-child(even) {
        background-color: #f2f2f2;
    }

    .btn-edit {
        padding: 5px 10px;
        font-size: 14px;
    }

    .bold-text {
        font-weight: bold;
    }
</style>
{% endblock %}

{% block contenido %}
<div class="container mt-5">
    <h1 class="edit-heading">Listado de Tickets Emitidos</h1>
    <form class="search-form" method="get">
        <label for="search_usuario">Filtrar por Usuarios:</label>
        <input type="text" id="search_usuario" name="search_usuario" value="{{ request.GET.search_usuario }}">
        <button type="submit">Buscar</button>
    </form>
    {% if tickets %}
    <div class="table-container">
        <table class="table table-bordered table-hover">
            <thead class="table-dark">
                <tr>
                    <th>ID Ticket</th>
                    <th>Sede</th>
                    <th>Dirección</th>
                    <th>Área</th>
                    <th>Modalidad</th>
                    <th>Nombre</th>
                    <th>RUT</th>
                    <th class="bold-text">Usuario</th>
                    <th>Correo Institucional</th>
                    <th>Teléfono</th>
                    <th>Tipo de Reporte</th>
                    <th>IP</th>
                    <th>Hostname</th>
                    <th>Marca/Modelo</th>
                    <th>Solicitud</th>
                    <th>Fecha de Emisión</th>
                    <th>Editar</th>
                </tr>
            </thead>
            <tbody>
                {% for ticket in tickets %}
                <tr>
                    <td>{{ ticket.IdTicket }}</td>
                    <td>{{ ticket.get_Sede_display }}</td>
                    <td>{{ ticket.Direccion }}</td>
                    <td>{{ ticket.Area }}</td>
                    <td>{{ ticket.get_Modalidad_display }}</td>
                    <td>{{ ticket.Nombre }}</td>
                    <td>{{ ticket.Rut }}</td>
                    <td class="bold-text" >{{ ticket.Usuario }}</td>
                    <td>{{ ticket.CorreoInstitucional }}</td>
                    <td>{{ ticket.Telefono }}</td>
                    <td>{{ ticket.get_TipoReporte_display }}</td>
                    <td>{{ ticket.IP }}</td>
                    <td>{{ ticket.HOSTNAME }}</td>
                    <td>{{ ticket.MARCA_MODELO }}</td>
                    <td>{{ ticket.Solicitud }}</td>
                    <td>{{ ticket.FechaEmision }}</td>
                    <td>
                        <a href="{% url 'editar_ticket' ticket.IdTicket %}" class="btn btn-link btn-sm btn-edit">Editar</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
    <p class="no-tickets-message">No se han emitido tickets.</p>
    {% endif %}
</div>
{% endblock %}

ticketera/app/templates/app/registrar_ticket.html
{% extends 'app/base.html' %}

{% load static %}

{% block js %}
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    // Función para mostrar un SweetAlert2 cuando se emite el ticket
    document.addEventListener('DOMContentLoaded', () => {
        const form = document.querySelector('form');
        
        form.addEventListener('submit', (event) => {
            event.preventDefault(); // Evitar el envío del formulario
            
            Swal.fire({
                title: 'Confirmar',
                text: '¿Desea emitir este ticket?',
                icon: 'question',
                showCancelButton: true,
                confirmButtonText: 'Sí, emitir',
                cancelButtonText: 'Cancelar'
            }).then((result) => {
                if (result.isConfirmed) {
                    form.submit(); // Enviar el formulario si el usuario confirma
                }
            });
        });
    });
</script>
{% endblock %}

{% block css %}
<style>
    .edit-heading {
        font-size: 2.5rem;
        font-weight: bold;
        margin-bottom: 1rem;
    }
</style>
<style>
    /* Estilos personalizados */
    .custom-form-label {
        font-weight: bold;
    }
    .custom-form-field {
        margin-bottom: 15px;
    }
    .custom-form-submit {
        margin-top: 20px;
    }
</style>
{% endblock %}

{% block contenido %}
<div class="container mt-5">
    <h1 class="edit-heading">Regitrar Ticket</h1>
    <form method="post" action="{% url 'registrar_ticket' %}" class="needs-validation" novalidate>
        {% csrf_token %}
        {% for field in form %}
            <div class="mb-3 custom-form-field">
                <label for="{{ field.id_for_label }}" class="form-label custom-form-label">{{ field.label }}</label>
                {{ field }}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary custom-form-submit" >Registrar</button>
    </form>
</div>
{% endblock %}